services:
  app:
    build: .
    container_name: lab6-app
    ports: ["8086:5000"]
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 128M
  worker:
    image: alpine
    container_name: lab6-worker
    command: ["sh","-c","while true; do echo batch-job-$(date +%s); sleep 10; done"]
