services:
  app:
    image: nginx:alpine
    ports: ["8089"]
  proxy:
    image: nginx:alpine
    container_name: lab9-proxy
    ports: ["8089:80"]
    volumes: ["./nginx.conf:/etc/nginx/nginx.conf:ro"]
